learner         :       AUG
dataset         :       tiny
mem_iters       :       1
n_augs          :       2
n_tasks         :       20
optim           :       SGD
lr              :       0.07
mem_size        :       5000
batch_size      :       100
mem_batch_size  :       200
tag             :       2aug,tiny,mi1
mix_coef        :       0.5
mixup           :       False
