
learner         :       AUG
dataset         :       tiny
mem_iters       :       20
n_augs          :       4
n_tasks         :       20
optim           :       SGD
lr              :       0.07
mem_size        :       10000
mem_batch_size  :       200
batch_size      :       100
tag             :       4aug,1mixup,1cutmix,1style,tiny,mi20
n_mixup         :       1
n_cutmix        :       1
n_styles        :       1
min_mix         :       0.5
max_mix         :       1
style_samples   :       1
