training_type   :       inc
learner         :       CE
dataset         :       tiny
optim           :       SGD
lr              :       0.07
batch_size      :       100
supervised      :       True
epochs          :       1
tag             :       finetune,tiny
