training_type   :       uni
learner         :       CE
dataset         :       tiny
optim           :       SGD
lr              :       0.07
batch_size      :       128
supervised      :       True
epochs          :       50
tag             :       offline,tiny
