
learner         :       AGEM
dataset         :       cifar100
mem_iters       :       1
n_tasks         :       10
optim           :       SGD
lr              :       0.07
mem_size        :       5000
batch_size      :       100
mem_batch_size  :       200
tag             :       agem,cifar100,mi1
