
learner         :       LUMP
dataset         :       cifar100
mem_iters       :       1
n_tasks         :       10
optim           :       SGD
lr              :       0.07
mem_size        :       5000
mem_batch_size  :       200
batch_size      :       100
tag             :       lump,cifar100,mi1
