
learner         :       SCR
dataset         :       cifar100
mem_iters       :       1
n_tasks         :       10
optim           :       SGD
lr              :       0.07
mem_size        :       2000
batch_size      :       100
mem_batch_size  :       200
supervised      :       True
tag             :       scr,cifar100,mi1
