
learner         :       LUMP
dataset         :       cifar10
mem_iters       :       1
n_tasks         :       5
optim           :       SGD
lr              :       0.07
mem_size        :       200
mem_batch_size  :       200
batch_size      :       100
tag             :       lump,cifar10,mi1
