
learner         :       SCR
dataset         :       cifar10
mem_iters       :       1
n_tasks         :       5
optim           :       SGD
lr              :       0.07
mem_size        :       200
batch_size      :       100
mem_batch_size  :       200
supervised      :       True
tag             :       scr,cifar10,mi1
